# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GraphKit', :git => 'https://github.com/michalkonturek/GraphKit', :branch => 'master'
end
